# News

## 2025-11-18

 - Added 2023 and 2024 data for all states
 - Amendments to date and time fields
    - Fixed incorrect *date_time_utc* UTC timestamps for Victorian observations for 2021 and 2022 data
    - Fixed incorrect *date* and *hour* fields for NSW 2018 hourly observations (hour incorrectly specified one hour early) - previously labelled with local time between 2007-12-31 23:00 to 2008-12-31 21:00
    - Fixed incorrect *year* labels for the last hour of each year in the hourly observation tables for NSW, NT, SA
        - incorrect year is that of the following year (e.g. 1995-12-31 23:00 was incorrectly labelled as year = 1996)
 - Alignment with standard variable and unit naming
    - Amendment of *variable* 'wind_dir_stddev' to 'wind_direction_std_dev' and *units* 'w/m*' to 'W_per_m2' for WA 2021-2022 observation data
    - Amendment of *variable* 'solar_radiation' to 'solar' for NT 2020-2022 observation data

## 2025-10-20

 - Added 2009 data for Queensland

## 2025-07-23

 - Amended data for ACT, replacing misidentified rolling means with 1-hrly averaged data
    - CO (replaced 8hr-rolling means with 1-hrly averages) for 2011 to 2020
    - PM~10~ (replaced 24hr-rolling means with 1-hrly averages) for 2011 to 2020
    - PM~2.5~ (replaced 24hr-rolling means with 1-hrly averages) for 2014 to 2020, removed 24hr-rolling means from 2013
    
## 2024-11-18

 - Replaced 2020 QLD data with full year of validated data
 - Removed irrelevant monitor sites (non-air pollution monitoring)
 - Fixed *station_id* and *station* for observations attached to the incorrect set of coordinates for that site (where station has moved)

## 2024-11-14

 - Added 2021 and 2022 data for all states
 - Updated stations to reflect station movement

## 2024-11-05

 - Corrected datetime fields for NT 2011-2017 where observations with hour 0 were assigned to the wrong date
 - Corrected datetime fields for ACT, NT and WA to be hour-beginning in line with other states and territories

## Archived

### 2023-11-19
 
 - Removed all non-1hrly averages from ap_monitor_data_master table
 - Corrected date_time_utc field
 - Removed QLD observations in 2020 where value = -9999
 
### 2022-01-20

 - Licence for Tas EPA data updated.
