# Using NAPMD

The NAPMD is freely available to researchers. Access is granted individually on [request to CARDAT][cardat-email] - please put NAPMD access in the subject line to assist with granting access sooner. You will be asked to read and acknowledge [conditions of use and disclaimers](#conditions-of-use) prior to being given access.

## Accessing the database

Users can choose between an API login or a database login. The API allows for easier but less flexible retrieval of data by providing specific parameters (e.g. station ID, parameter name, datetime). Using a database connection is more flexible but requires knowledge of SQL queries. See the [Appendix](#querying-napmd) for `R` (API functions) and `SQL` (database queries) code snippets.

Data in NAPMD is subject to change as new, updated or amended data becomes available. We strongly recommend you save a copy of extracted data for your analysis if reproducibility is required.

## Cite the data and report outcomes

In your publications using these data please remember to abide by the [conditions of use](#conditions-of-use), in particular:

 - cite the National Air Pollution Monitoring Database
 - [contact Tas EPA][tas-contact] to confirm usage is acceptable (if [using Tasmanian data](#tas-conditions))
 - cite the relevant NSW paper (if [using NSW data](#nsw-conditions))
 - report usage back to us so we can let the relevant state and territory organisations know how their data are being used [car.data@sydney.edu.au][11]

## Using the database

Air pollution data is stored in the database in tables by state and year. If you are querying the database directly, you will most usually want to access more than one state's or year's worth of data at once, which can be done via the following tables:

 - ap_monitor_data_master: 1-hrly averaged data
 - ap_monitor_data_daily_master: daily averaged data (available where hourly averaged data is not available)
 - ap_monitor_locations_master: station location data
 
For recent years, most data is available by hour only and is not included in the daily averaged data. The exception is Tasmanian data, which provides daily averages from the BlanKeT network. The daily data table also include historical data that is otherwise not available by hour.

## Questions about the data, and reporting improbable values

The NAPMD is a collaborative database between the [state and territory governments](#acknowledgements), the [Centre for Safe Air][centre-air-home] and our users. We ask that you contact us (car.data@sydney.edu.au) with any question about the data or improbable values you find so that we can ensure the data is being used in a fit for purpose manner and is of the highest quality.
